<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.10">
  <POU Name="EM_Template" Id="{4c58fcab-0c4e-44d2-958d-5966280c363d}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK EM_Template EXTENDS FB_EM_Base IMPLEMENTS ITF_EM_Template
VAR
// Local variables
	
// Config Struct
	s_stConfig						: ST_EM_Template_Config;
	
// Control modules
	// n.a.
	
// Inputs
	// n.a.
	
// Outputs
	// n.a.
	
// Alarms
	// n.a.
	
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[SUPER^();


]]></ST>
    </Implementation>
    <Folder Name="Basic" Id="{c388fe87-eb83-464b-87de-602fe4fe0cbf}" />
    <Folder Name="itfEM_Template" Id="{d7508406-5702-4329-8b61-48b06afc9484}" />
    <Folder Name="OMAC PackML" Id="{3a08366a-ef8f-4f92-b7f1-5e107f704d0d}" />
    <Method Name="_m_Alarms" Id="{305634a4-4787-42f7-a478-02ef40ad8999}" FolderPath="Basic\">
      <Declaration><![CDATA[METHOD PROTECTED _m_Alarms]]></Declaration>
      <Implementation>
        <ST><![CDATA[SUPER^._m_Alarms();

// Alarm description
	// Configuration
	// n.a.
	// Call
	// n.a.







]]></ST>
      </Implementation>
    </Method>
    <Method Name="_m_Modules" Id="{18e9756f-350b-4c62-ae92-97b2dd506529}" FolderPath="Basic\">
      <Declaration><![CDATA[METHOD PROTECTED _m_Modules]]></Declaration>
      <Implementation>
        <ST><![CDATA[SUPER^._m_Modules();

// Description of CM
	// n.a.
	
	
	]]></ST>
      </Implementation>
    </Method>
    <Property Name="p_rstConfig" Id="{511eb571-1518-4b73-8dd5-92b5a3f3cd4c}" FolderPath="itfEM_Template\">
      <Declaration><![CDATA[{attribute 'monitoring' := 'call'}
PROPERTY p_rstConfig : REFERENCE TO ST_EM_Template_Config]]></Declaration>
      <Get Name="Get" Id="{57648b8b-7208-4205-947c-0f251eebf744}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[p_rstConfig := s_stConfig;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <LineIds Name="EM_Template">
      <LineId Id="9" Count="0" />
      <LineId Id="219" Count="1" />
      <LineId Id="187" Count="0" />
    </LineIds>
    <LineIds Name="EM_Template._m_Alarms">
      <LineId Id="52" Count="0" />
      <LineId Id="102" Count="0" />
      <LineId Id="93" Count="0" />
      <LineId Id="126" Count="2" />
      <LineId Id="125" Count="0" />
      <LineId Id="54" Count="0" />
      <LineId Id="124" Count="0" />
      <LineId Id="83" Count="4" />
      <LineId Id="11" Count="0" />
    </LineIds>
    <LineIds Name="EM_Template._m_Modules">
      <LineId Id="5" Count="0" />
      <LineId Id="73" Count="0" />
      <LineId Id="186" Count="0" />
      <LineId Id="190" Count="0" />
      <LineId Id="166" Count="0" />
      <LineId Id="188" Count="1" />
    </LineIds>
    <LineIds Name="EM_Template.p_rstConfig.Get">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>