<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.10">
  <POU Name="HMI_EM_Template_Gain" Id="{ee1a0384-e929-4b85-8e7a-f49b8c162404}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK HMI_EM_Template_Gain EXTENDS FB_HMI_Base
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
	s_itfEmTemplate			: ITF_EM_Template; // Upgraded Interface from Control module
// Hmi Control Modules 
	// n.a.
// Hmi Alarms
	// n.a.
// Local vars
	// n.a.
	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[SUPER^();




]]></ST>
    </Implementation>
    <Method Name="m_Main" Id="{de5865cd-34bc-46d4-874e-7964e72958e8}">
      <Declaration><![CDATA[METHOD PUBLIC m_Main]]></Declaration>
      <Implementation>
        <ST><![CDATA[SUPER^.m_Main();


// Upgrade the base-interface
IF NOT __QUERYINTERFACE(i_itfModule, s_itfEmTemplate) THEN
	RETURN;
END_IF

// Sub EMs
	// n.a.

// Control modules
	// CM_....
	// n.a.

]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="HMI_EM_Template_Gain">
      <LineId Id="28" Count="1" />
      <LineId Id="74" Count="1" />
      <LineId Id="54" Count="0" />
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="HMI_EM_Template_Gain.m_Main">
      <LineId Id="5" Count="0" />
      <LineId Id="11" Count="1" />
      <LineId Id="35" Count="3" />
      <LineId Id="44" Count="0" />
      <LineId Id="43" Count="0" />
      <LineId Id="45" Count="0" />
      <LineId Id="39" Count="3" />
      <LineId Id="25" Count="0" />
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>