<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="HMI_UN_Machine100_Gain" Id="{57345a9d-da5c-4006-9cd1-60c4c0a59f6f}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK HMI_UN_Machine100_Gain EXTENDS FB_HMI_Base
VAR
	s_itfUnMachine100		: ITF_UN_Machine100; // Upgraded Interface
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[SUPER^();

// Upgrade the base-interface
IF NOT __QUERYINTERFACE(i_itfModule, s_itfUnMachine100) THEN
	RETURN;
END_IF
]]></ST>
    </Implementation>
    <LineIds Name="HMI_UN_Machine100_Gain">
      <LineId Id="28" Count="4" />
      <LineId Id="22" Count="0" />
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>