<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4026.13">
  <POU Name="FB_Main" Id="{ce4e8b74-9023-48c1-875b-79162c03d5fc}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Main
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
// Areas
	s_fbArea100	: FB_Area100;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[// Areas
s_fbArea100();

]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>